version: '3'

services:
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT_CONTAINER}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: 'America/Chicago'
    # Set default time zone for the database
    command: postgres -c 'timezone=-06:00'
    expose:
      # Opens port on the container
      - '${DB_PORT_CONTAINER}'
      # Where our data will be persisted
    container_name: outfitme_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
# Names our volume
volumes:
  outfitme-db: