version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${DB_USER}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      # Set timezone
      TZ: 'America/Chicago'
    command: '--default-time-zone=-06:00'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '${DB_PORT_EXPOSED}:${DB_PORT}'
    expose:
      # Opens port on the container
      - '${DB_PORT}'
      # Where our data will be persisted
    volumes:
      - outfitme-db:/var/lib/mysql
# Names our volume
volumes:
  outfitme-db: